### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by nourlabs** [matrix-io/matrix-lite-nfc-js#10]
hello ,
I'm having this error message when I launch MATRIX-Lite-NFC-JS 

/home/pi/projects/bot/node_modules/@matrix-io/matrix-lite-nfc/lib/read.js:8
  _readLoop = undefined;
            ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/projects/bot/node_modules/@matrix-io/matrix-lite-nfc/index.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

**Comment by Hermitter** [comment]
Fixed in your PR #11. 
The [npm package](https://www.npmjs.com/package/@matrix-io/matrix-lite-nfc) has been updated as well.

Thanks!
